### ISSUE TITLE
Episode doesn't play after a phone call is done

### ISSUE THREAD

**Issue by MichaelApproved** [KeithAndTheGirl/iOS#105]
When I'm listening to a show and take a phone call, the episode pauses. After the phone call is over, the episode should resume.

1) Play an episode
2) Make a phone call
-- episode pauses
3) end phone call
-- nothing happens.

What should happen is, after step 3, the episode should resume playing.

**Comment by Nick-R** [comment]
Michael,

Please try it in build_50
