### ISSUE TITLE
App crashes without internet

### ISSUE THREAD

**Issue by MichaelApproved** [KeithAndTheGirl/iOS#106]
I'm getting a report from a tester that the app is crashing when they don't have internet service. I couldn't reproduce this myself but is there a way we can get the crash logs from their app?

**Comment by Nick-R** [comment]
Michael,

I also can't reproduce it. 

There is a way for users to automatically send crash reports to iTunesConenct, here: https://support.apple.com/es-la/HT202100 ( "Share With App Developers" should be activated)

Plus, there in settings there are all crash reports, he can go, find and send one (by copy the text).

**Comment by MichaelApproved** [comment]
OK. I set mine to automatically send developers crash reports. I'll see Keith tomorrow and get him setup to do the same. I'll also look for any recent reports and send them to you. Thanks!
