### ISSUE TITLE
AirPlay

### ISSUE THREAD

**Issue by MichaelApproved** [KeithAndTheGirl/iOS#72]
How much time would it take to integrate AirPlay into the app for audio and video?

**Comment by MichaelApproved** [comment]
@Nick-R Are you able to use an mp4 for airplay or does it have to be an HLS stream?

**Comment by Nick-R** [comment]
Michael,

For me it's hard to check this. As i know, mp4 should work for AirPlay. Did you try?

**Comment by MichaelApproved** [comment]
I haven't tried mp4 but I realize that it won't matter anyway because we use an HLS stream.

I'll test a few things on my side and consider new approaches to authentication. In the meantime, I'll close this issue.
