### ISSUE TITLE
Rewind audio when the headset is double clicked

### ISSUE THREAD

**Issue by MichaelApproved** [KeithAndTheGirl/iOS#91]
Right now, when you double click the headset, it fast forwards 15 seconds. Instead, please rewind the audio 15 seconds.

Also, is there an option for triple clicking the headset?

**Comment by MichaelApproved** [comment]
The episode rewinds 30 seconds. Can you please have it rewind 15 seconds?

**Comment by Nick-R** [comment]
Michael, 

From the code point of view this two events are absolutely identical:
- double click on remote control (headset)
- forward button on lock screen

So we can handle it only one way, we can't separate this two events. If we make it rewind, it will work for headset, but both buttons on lock screen (backward and forward buttons) will rewind the audio. This buggy behavior should be in our current testflight version, please check.

So, rewind forward for headset double click is something like default behavior which we can't change.

**Comment by Nick-R** [comment]
BTW, standard headset gesture to rewind is triple click. And it's also working for us (at least in new build).

**Comment by MichaelApproved** [comment]
Makes sense. It now works as you described. Thanks!
